version: '3.8'

services:
  e-commerce:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-commerce

    ports:
      - '5500:5500'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
