name: CI/CD Pipeline

# Trigger the workflow on push to the 'main' branch or pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest # Runs the tests on the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Checkout the repository

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.0' # Use the Node.js version you want

      - name: Install dependencies
        run: npm install # Install your dependencies

      - name: Build App
        run: npm run build # Build the app

      - name: Run Jest tests
        run: npm run test # Run the Jest tests defined in package.json

  build-docker:
    runs-on: ubuntu-latest # Runs the Docker build on the latest Ubuntu environment
    needs: test # Ensure this job only runs after the 'test' job passes

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Checkout the repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # Set up Docker Buildx

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: |
          docker build . -t kiramiz/e-commerce:${{ github.sha }} # Replace with your image name

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Add your Docker Hub username to GitHub secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Add your Docker Hub password to GitHub secrets

      - name: Push Docker image
        run: |
          docker push kiramiz/e-commerce:${{ github.sha }} # Replace with your image name

  deploy:
    runs-on: ubuntu-latest
    needs: build-docker # Ensure deploy job runs after the build job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH to Hostinger VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_VPS_IP }} # IP address of VPS
          username: ${{ secrets.HOSTINGER_VPS_USER }} # VPS SSH username
          key: ${{ secrets.HOSTINGER_SSH_KEY }} # SSH private key for login
          port: 22
          script: |
            # Pull the latest Docker image and restart the app on your VPS
            docker pull kiramiz/e-commerce:${{ github.sha }} # Pull the new image tagged with the commit SHA
            # docker pull kiramiz/e-commerce:latest # Optionally, pull the latest tag if you want the latest image
            docker-compose --env-file /home/global/e-commerce/.env -f /home/global/e-commerce/docker-compose.yml up -d
      - name: Send Slack notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment completed successfully for commit: '${{ github.sha }}'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
